name: Check Pandas Version
on: [push, pull_request]
jobs:
  check-pandas-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Check Pandas Version
        run: |
          python -c "import pandas as pd; assert pd.__version__ >= '1.5.3'"
